### ISSUE TITLE
Cannot use ak.wwise.waapi.getSchema because the uri keyword is used in WaapiClient.call

### ISSUE THREAD

**Issue by ak-slongchamps** [audiokinetic/waapi-client-python#5]
Because the WaapiClient functions and the argument schema for the WAAPI call both expect a uri argument, merging of the arguments leads to a clash between the two.

Workaround the issue by changing the positional argument name in WaapiClient.call to _uri, which should never be used by any WAAPI function or topic.

**Comment by zcyh147** [comment]
Looking forward to the resolution of this issue, Thank you Samuel!
