### ISSUE TITLE
Cannot use ak.wwise.waapi.getFunctions to get the APIs of Topics (Subscription API)

### ISSUE THREAD

**Issue by zcyh147** [audiokinetic/waapi-client-python#6]
WAAPI's `ak.wwise.waapi.getFunctions` can only get the APIs in the Topics category, I was wondering if `ak.wwise.waapi.getFunctions` could add support for APIs under the Subscription category?

**Comment by ak-slongchamps** [comment]
`ak.wwise.waapi.getTopics` is what you are searching for.
https://www.audiokinetic.com/library/edge/?source=SDK&id=ak_wwise_waapi_gettopics.html

**Comment by zcyh147** [comment]
Oh my god, I suddenly realized that I clearly wrote in the article that `ak.wwise.waapi.getTopics` can do this, I must have been dizzy yesterday, thanks a lot!
